In [133]:
import pandas as pd
df_r = pd.read_csv('8000ethnicity.txt', delimiter = "\t", header=None)
df_s = pd.read_csv('8000gender.txt', delimiter = "\t", header=None)
df = pd.concat([df_r, df_s])
df.columns = ['Tweet']
df = df.sample(frac=1).reset_index(drop=True) #randomising rows

In [134]:
df

                                                   Tweet
0      Stfu! RT @imThatDUDE_BM: @smokee_banks lol Cha...
1            They make rape jokes and call eachother gay
2      poc tell y'all constantly that there's a racis...
3      I’ve had two before u, but one i hated with my...
4      FFS a can opener is too technical for the skan...
...                                                  ...
15929  RT @GlobeAlone: I was sure they'd roll Lynn ou...
15930  Because they can't play with white kids? I thi...
15931  It’s trying to get it nit steal it. You know. ...
15932  So @Schwarziest got suspended from @twitter ag...
15933  Yet, a Black Man, who heard a white man at a r...

[15934 rows x 1 columns]

In [135]:
tweets = df['Tweet'].tolist()

In [136]:
from nltk.tokenize import TweetTokenizer #I chose to tokenize with this, as it gets rid of @ handlers
tknzr = TweetTokenizer(preserve_case=True, reduce_len=False, strip_handles=True)

lst = []

for tweet in tweets:    
    if type(tweet) != str: #removing tweets that are not 'tokenizable'
        pass
    else:
        lst.append(tknzr.tokenize(tweet))

In [156]:
import nltk
from nltk.corpus import stopwords
stop_words = nltk.corpus.stopwords.words('english')
from nltk.tokenize import RegexpTokenizer
from nltk.stem import PorterStemmer 
ps = PorterStemmer() 

remove = "!$%&()*+rt, .-./:;<=>?@[\]^_`’{|}~]’\wdiwj/'0123456789......\"\x92\\n\r\“\”"

In [157]:
ft_infinitive = [] #filtered tokens with verbs in infinitive tense
for tweet in lst:
    filt = []
    for token in tweet:
        if 'http' in token.lower():
            continue
        if token.lower() in remove:
            continue
        if token.lower() in stop_words:
            continue
        if token.lower() == 'rt':
            continue
        else:
            filt.append((nltk.WordNetLemmatizer().lemmatize(token.lower(), 'v')))
    ft_infinitive.append(filt)

In [158]:
ft_finite = [] #filtered tokens with verbs in finite tense
for tweet in lst:
    filt = []
    for token in tweet:
        if 'http' in token.lower():
            continue
        if token.lower() in remove:
            continue
        if token.lower() in stop_words:
            continue
        if token.lower() == 'rt':
            continue        
        else:
            filt.append((nltk.WordNetLemmatizer().lemmatize(token.lower())))
    ft_finite.append(filt)
   # [' '.join(i) for i in X_test]

In [169]:
f_f = [' '.join(i) for i in ft_finite]
f_i = [' '.join(i) for i in ft_infinitive]
#converting lists of tokens into sentences

In [167]:
df = pd.DataFrame([f_i])
df8000inf = df.transpose()

In [168]:
df8000inf

                                                       0
0          stfu lol chaunasee brittane dumb niggers fuck
1                      make rape joke call eachother gay
2      poc tell y'all constantly there's racism probl...
3      two u one hat gut close friend lose touch hayy...
4                   ffs opener technical skanky hoe #mkr
...                                                  ...
15929  sure they'd roll lynn like violet beauregarde ...
15930  can't play white kid think go back history bla...
15931  try get nit steal know way biden anything get ...
15932  get suspend apparently make rape joke fine res...
15933  yet black man hear white man retail store call...

[15934 rows x 1 columns]

In [170]:
df = pd.DataFrame([f_f])
df8000fin = df.transpose()

In [171]:
df8000fin

                                                       0
0           stfu lol chaunasee brittane dumb nigger fuck
1                      make rape joke call eachother gay
2      poc tell y'all constantly there's racism probl...
3      two u one hated gut close friend lost touch ha...
4                   ffs opener technical skanky hoe #mkr
...                                                  ...
15929  sure they'd roll lynn like violet beauregarde ...
15930  can't play white kid think going back history ...
15931  trying get nit steal know way biden anything g...
15932  got suspended apparently making rape joke fine...
15933  yet black man heard white man retail store cal...

[15934 rows x 1 columns]